// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/micro_mall_trolley_proto/trolley_business/trolley_business.proto

package trolley_business

import (
	context "context"
	fmt "fmt"
	_ "gitee.com/kelvins-io/common/proto/google/api"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RetCode int32

const (
	RetCode_SUCCESS            RetCode = 0
	RetCode_ERROR              RetCode = 500
	RetCode_USER_NOT_EXIST     RetCode = 50001
	RetCode_USER_EXIST         RetCode = 50002
	RetCode_MERCHANT_NOT_EXIST RetCode = 50003
	RetCode_MERCHANT_EXIST     RetCode = 50004
	RetCode_SHOP_NOT_EXIST     RetCode = 50005
	RetCode_SHOP_EXIST         RetCode = 50006
	RetCode_SKU_NOT_EXIST      RetCode = 50007
	RetCode_SKU_EXIST          RetCode = 50008
)

var RetCode_name = map[int32]string{
	0:     "SUCCESS",
	500:   "ERROR",
	50001: "USER_NOT_EXIST",
	50002: "USER_EXIST",
	50003: "MERCHANT_NOT_EXIST",
	50004: "MERCHANT_EXIST",
	50005: "SHOP_NOT_EXIST",
	50006: "SHOP_EXIST",
	50007: "SKU_NOT_EXIST",
	50008: "SKU_EXIST",
}

var RetCode_value = map[string]int32{
	"SUCCESS":            0,
	"ERROR":              500,
	"USER_NOT_EXIST":     50001,
	"USER_EXIST":         50002,
	"MERCHANT_NOT_EXIST": 50003,
	"MERCHANT_EXIST":     50004,
	"SHOP_NOT_EXIST":     50005,
	"SHOP_EXIST":         50006,
	"SKU_NOT_EXIST":      50007,
	"SKU_EXIST":          50008,
}

func (x RetCode) String() string {
	return proto.EnumName(RetCode_name, int32(x))
}

func (RetCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c7bbf49fb9873edd, []int{0}
}

type OperationType int32

const (
	OperationType_CREATE   OperationType = 0
	OperationType_UPDATE   OperationType = 1
	OperationType_DELETE   OperationType = 2
	OperationType_AUDIT    OperationType = 3
	OperationType_PUT_AWAY OperationType = 4
)

var OperationType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
	3: "AUDIT",
	4: "PUT_AWAY",
}

var OperationType_value = map[string]int32{
	"CREATE":   0,
	"UPDATE":   1,
	"DELETE":   2,
	"AUDIT":    3,
	"PUT_AWAY": 4,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c7bbf49fb9873edd, []int{1}
}

type RemoveSkuRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SkuCode              string   `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	ShopId               int64    `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSkuRequest) Reset()         { *m = RemoveSkuRequest{} }
func (m *RemoveSkuRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveSkuRequest) ProtoMessage()    {}
func (*RemoveSkuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7bbf49fb9873edd, []int{0}
}

func (m *RemoveSkuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSkuRequest.Unmarshal(m, b)
}
func (m *RemoveSkuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSkuRequest.Marshal(b, m, deterministic)
}
func (m *RemoveSkuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSkuRequest.Merge(m, src)
}
func (m *RemoveSkuRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveSkuRequest.Size(m)
}
func (m *RemoveSkuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSkuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSkuRequest proto.InternalMessageInfo

func (m *RemoveSkuRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RemoveSkuRequest) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *RemoveSkuRequest) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type RemoveSkuResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RemoveSkuResponse) Reset()         { *m = RemoveSkuResponse{} }
func (m *RemoveSkuResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveSkuResponse) ProtoMessage()    {}
func (*RemoveSkuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7bbf49fb9873edd, []int{1}
}

func (m *RemoveSkuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSkuResponse.Unmarshal(m, b)
}
func (m *RemoveSkuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSkuResponse.Marshal(b, m, deterministic)
}
func (m *RemoveSkuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSkuResponse.Merge(m, src)
}
func (m *RemoveSkuResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveSkuResponse.Size(m)
}
func (m *RemoveSkuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSkuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSkuResponse proto.InternalMessageInfo

func (m *RemoveSkuResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

type JoinSkuRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SkuCode              string   `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	ShopId               int64    `protobuf:"varint,3,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Count                int64    `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Selected             bool     `protobuf:"varint,6,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinSkuRequest) Reset()         { *m = JoinSkuRequest{} }
func (m *JoinSkuRequest) String() string { return proto.CompactTextString(m) }
func (*JoinSkuRequest) ProtoMessage()    {}
func (*JoinSkuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7bbf49fb9873edd, []int{2}
}

func (m *JoinSkuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinSkuRequest.Unmarshal(m, b)
}
func (m *JoinSkuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinSkuRequest.Marshal(b, m, deterministic)
}
func (m *JoinSkuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinSkuRequest.Merge(m, src)
}
func (m *JoinSkuRequest) XXX_Size() int {
	return xxx_messageInfo_JoinSkuRequest.Size(m)
}
func (m *JoinSkuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinSkuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinSkuRequest proto.InternalMessageInfo

func (m *JoinSkuRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *JoinSkuRequest) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *JoinSkuRequest) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *JoinSkuRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *JoinSkuRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *JoinSkuRequest) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

type JoinSkuResponse struct {
	Common               *CommonResponse `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JoinSkuResponse) Reset()         { *m = JoinSkuResponse{} }
func (m *JoinSkuResponse) String() string { return proto.CompactTextString(m) }
func (*JoinSkuResponse) ProtoMessage()    {}
func (*JoinSkuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7bbf49fb9873edd, []int{3}
}

func (m *JoinSkuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinSkuResponse.Unmarshal(m, b)
}
func (m *JoinSkuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinSkuResponse.Marshal(b, m, deterministic)
}
func (m *JoinSkuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinSkuResponse.Merge(m, src)
}
func (m *JoinSkuResponse) XXX_Size() int {
	return xxx_messageInfo_JoinSkuResponse.Size(m)
}
func (m *JoinSkuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinSkuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinSkuResponse proto.InternalMessageInfo

func (m *JoinSkuResponse) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

type CommonResponse struct {
	Code                 RetCode  `protobuf:"varint,1,opt,name=code,proto3,enum=trolley_business.RetCode" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7bbf49fb9873edd, []int{4}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetCode() RetCode {
	if m != nil {
		return m.Code
	}
	return RetCode_SUCCESS
}

func (m *CommonResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("trolley_business.RetCode", RetCode_name, RetCode_value)
	proto.RegisterEnum("trolley_business.OperationType", OperationType_name, OperationType_value)
	proto.RegisterType((*RemoveSkuRequest)(nil), "trolley_business.RemoveSkuRequest")
	proto.RegisterType((*RemoveSkuResponse)(nil), "trolley_business.RemoveSkuResponse")
	proto.RegisterType((*JoinSkuRequest)(nil), "trolley_business.JoinSkuRequest")
	proto.RegisterType((*JoinSkuResponse)(nil), "trolley_business.JoinSkuResponse")
	proto.RegisterType((*CommonResponse)(nil), "trolley_business.CommonResponse")
}

func init() {
	proto.RegisterFile("proto/micro_mall_trolley_proto/trolley_business/trolley_business.proto", fileDescriptor_c7bbf49fb9873edd)
}

var fileDescriptor_c7bbf49fb9873edd = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x75, 0x7e, 0xa7, 0x34, 0x35, 0x43, 0x55, 0xdc, 0x1c, 0x20, 0x84, 0x4b, 0x15, 0xa9,
	0xb5, 0x28, 0x17, 0xc4, 0x01, 0x29, 0xa4, 0x46, 0x2d, 0xfd, 0x49, 0x59, 0x3b, 0xa2, 0x9c, 0xac,
	0xd4, 0x59, 0x85, 0x25, 0xb6, 0x37, 0x64, 0xed, 0x48, 0xbd, 0x72, 0xc8, 0x0b, 0x70, 0xe5, 0x81,
	0xb8, 0x42, 0xf9, 0x7b, 0x00, 0x1e, 0x81, 0x3b, 0xc8, 0xbb, 0x6e, 0x94, 0x36, 0x55, 0x2f, 0x70,
	0x9b, 0xf9, 0xe6, 0xf3, 0x37, 0x7f, 0x3b, 0x86, 0xe7, 0xc3, 0x11, 0x8f, 0xb9, 0x15, 0x32, 0x7f,
	0xc4, 0xbd, 0xb0, 0x1b, 0x04, 0x5e, 0x3c, 0xe2, 0x41, 0x40, 0x4f, 0x3d, 0x15, 0x38, 0xf7, 0x4e,
	0x12, 0xc1, 0x22, 0x2a, 0xc4, 0x1c, 0xb0, 0x29, 0x79, 0x68, 0x5c, 0xc6, 0xab, 0x4f, 0xfb, 0x2c,
	0xa6, 0x74, 0xd3, 0xe7, 0xa1, 0x35, 0xa0, 0xc1, 0x98, 0x45, 0x62, 0x83, 0x71, 0xcb, 0xe7, 0x61,
	0xc8, 0x23, 0x4b, 0x89, 0xf7, 0x39, 0xef, 0x07, 0xd4, 0xea, 0x0e, 0x99, 0xd5, 0x8d, 0x22, 0x1e,
	0x77, 0x63, 0xc6, 0xa3, 0x4c, 0xb1, 0x7e, 0x0c, 0x06, 0xa1, 0x21, 0x1f, 0x53, 0x67, 0x90, 0x10,
	0xfa, 0x2e, 0xa1, 0x22, 0x46, 0x03, 0xf4, 0x84, 0xf5, 0x4c, 0xad, 0xa6, 0xad, 0xeb, 0x24, 0x35,
	0x71, 0x0d, 0x4a, 0x62, 0x90, 0x78, 0x3e, 0xef, 0x51, 0x73, 0xa1, 0xa6, 0xad, 0x97, 0x49, 0x51,
	0x0c, 0x92, 0x16, 0xef, 0x51, 0xbc, 0x03, 0x45, 0xf1, 0x86, 0x0f, 0x3d, 0xd6, 0x33, 0x75, 0xf9,
	0x41, 0x21, 0x75, 0x77, 0x7b, 0xf5, 0x03, 0xb8, 0x35, 0xa3, 0x2c, 0x86, 0x3c, 0x12, 0x14, 0x1f,
	0x43, 0x41, 0xd5, 0x26, 0xd5, 0x17, 0xb7, 0x6a, 0x9b, 0x73, 0x9d, 0xb6, 0x64, 0xfc, 0xfc, 0x0b,
	0x92, 0xf1, 0xeb, 0x1f, 0x35, 0xa8, 0xbc, 0xe0, 0x2c, 0xfa, 0xdf, 0x75, 0x22, 0x42, 0x2e, 0x66,
	0x21, 0x35, 0x73, 0x92, 0x2f, 0x6d, 0x5c, 0x81, 0xbc, 0xcf, 0x93, 0x28, 0x36, 0xf3, 0x92, 0xaa,
	0x1c, 0xac, 0x42, 0x49, 0xd0, 0x80, 0xfa, 0x31, 0xed, 0x99, 0x85, 0x9a, 0xb6, 0x5e, 0x22, 0x53,
	0xbf, 0xbe, 0x07, 0xcb, 0xd3, 0xea, 0xfe, 0xb9, 0xd7, 0x97, 0x50, 0xb9, 0x18, 0xc1, 0x0d, 0xc8,
	0xc9, 0xa6, 0x52, 0xa5, 0xca, 0xd6, 0xda, 0xbc, 0x12, 0xa1, 0x71, 0xda, 0x26, 0x91, 0xb4, 0x74,
	0x32, 0xa1, 0xe8, 0x67, 0x23, 0x48, 0xcd, 0xc6, 0x27, 0x0d, 0x8a, 0x19, 0x07, 0x17, 0xa1, 0xe8,
	0x74, 0x5a, 0x2d, 0xdb, 0x71, 0x8c, 0x1b, 0x08, 0x90, 0xb7, 0x09, 0x69, 0x13, 0xe3, 0xb7, 0x8e,
	0x2b, 0x50, 0xe9, 0x38, 0x36, 0xf1, 0x0e, 0xdb, 0xae, 0x67, 0x1f, 0xef, 0x3a, 0xae, 0xf1, 0x79,
	0xa2, 0xa3, 0x01, 0x20, 0x51, 0x85, 0x7c, 0x99, 0xe8, 0x68, 0x02, 0x1e, 0xd8, 0xa4, 0xb5, 0xd3,
	0x3c, 0x74, 0x67, 0xb8, 0x67, 0x13, 0xa9, 0x30, 0x8d, 0x28, 0xf4, 0xab, 0x42, 0x9d, 0x9d, 0xf6,
	0xd1, 0x0c, 0xf7, 0x9b, 0xd2, 0x95, 0xa8, 0x42, 0xbe, 0x4f, 0x74, 0xbc, 0x0d, 0x4b, 0xce, 0x5e,
	0x67, 0x86, 0xf6, 0x63, 0xa2, 0xe3, 0x32, 0x94, 0x53, 0x50, 0x01, 0x3f, 0x27, 0x7a, 0x63, 0x1f,
	0x96, 0xda, 0x43, 0x3a, 0x92, 0xcf, 0xd8, 0x3d, 0x1d, 0x52, 0x04, 0x28, 0xb4, 0x88, 0xdd, 0x74,
	0x6d, 0xd9, 0x4e, 0xa1, 0x73, 0xb4, 0x9d, 0xda, 0x5a, 0x6a, 0x6f, 0xdb, 0xfb, 0xb6, 0x6b, 0x1b,
	0x0b, 0x58, 0x86, 0x7c, 0xb3, 0xb3, 0xbd, 0xeb, 0x1a, 0x3a, 0xde, 0x84, 0xd2, 0x51, 0xc7, 0xf5,
	0x9a, 0xaf, 0x9a, 0xaf, 0x8d, 0xdc, 0xd6, 0x1f, 0x0d, 0x56, 0x5d, 0x35, 0xcd, 0x67, 0xd9, 0x30,
	0x1d, 0x3a, 0x1a, 0x33, 0x9f, 0x22, 0x87, 0x62, 0xb6, 0x53, 0xbc, 0x62, 0x77, 0x17, 0x1f, 0x63,
	0xf5, 0xfe, 0x35, 0x0c, 0xb5, 0xc4, 0xfa, 0xbd, 0xf7, 0x67, 0xbf, 0x3e, 0x2c, 0xac, 0x55, 0x57,
	0xac, 0xf1, 0xc3, 0xf3, 0x0b, 0xb7, 0xc4, 0x20, 0xb1, 0xde, 0x72, 0x16, 0x3d, 0xd1, 0x1a, 0x18,
	0x43, 0x79, 0x7a, 0x32, 0x58, 0xbf, 0x6a, 0xc9, 0x17, 0x2f, 0xb5, 0xfa, 0xe0, 0x5a, 0x4e, 0x96,
	0xf6, 0xae, 0x4c, 0x6b, 0x36, 0x56, 0x2f, 0xa7, 0x1d, 0x49, 0xea, 0x49, 0x41, 0xfe, 0x09, 0x1e,
	0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xbd, 0xda, 0xca, 0xa5, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TrolleyBusinessServiceClient is the client API for TrolleyBusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrolleyBusinessServiceClient interface {
	// 添加商品到购物车
	JoinSku(ctx context.Context, in *JoinSkuRequest, opts ...grpc.CallOption) (*JoinSkuResponse, error)
	// 从购物车移除商品
	RemoveSku(ctx context.Context, in *RemoveSkuRequest, opts ...grpc.CallOption) (*RemoveSkuResponse, error)
}

type trolleyBusinessServiceClient struct {
	cc *grpc.ClientConn
}

func NewTrolleyBusinessServiceClient(cc *grpc.ClientConn) TrolleyBusinessServiceClient {
	return &trolleyBusinessServiceClient{cc}
}

func (c *trolleyBusinessServiceClient) JoinSku(ctx context.Context, in *JoinSkuRequest, opts ...grpc.CallOption) (*JoinSkuResponse, error) {
	out := new(JoinSkuResponse)
	err := c.cc.Invoke(ctx, "/trolley_business.TrolleyBusinessService/JoinSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trolleyBusinessServiceClient) RemoveSku(ctx context.Context, in *RemoveSkuRequest, opts ...grpc.CallOption) (*RemoveSkuResponse, error) {
	out := new(RemoveSkuResponse)
	err := c.cc.Invoke(ctx, "/trolley_business.TrolleyBusinessService/RemoveSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrolleyBusinessServiceServer is the server API for TrolleyBusinessService service.
type TrolleyBusinessServiceServer interface {
	// 添加商品到购物车
	JoinSku(context.Context, *JoinSkuRequest) (*JoinSkuResponse, error)
	// 从购物车移除商品
	RemoveSku(context.Context, *RemoveSkuRequest) (*RemoveSkuResponse, error)
}

// UnimplementedTrolleyBusinessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTrolleyBusinessServiceServer struct {
}

func (*UnimplementedTrolleyBusinessServiceServer) JoinSku(ctx context.Context, req *JoinSkuRequest) (*JoinSkuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinSku not implemented")
}
func (*UnimplementedTrolleyBusinessServiceServer) RemoveSku(ctx context.Context, req *RemoveSkuRequest) (*RemoveSkuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSku not implemented")
}

func RegisterTrolleyBusinessServiceServer(s *grpc.Server, srv TrolleyBusinessServiceServer) {
	s.RegisterService(&_TrolleyBusinessService_serviceDesc, srv)
}

func _TrolleyBusinessService_JoinSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinSkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrolleyBusinessServiceServer).JoinSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trolley_business.TrolleyBusinessService/JoinSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrolleyBusinessServiceServer).JoinSku(ctx, req.(*JoinSkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrolleyBusinessService_RemoveSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrolleyBusinessServiceServer).RemoveSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trolley_business.TrolleyBusinessService/RemoveSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrolleyBusinessServiceServer).RemoveSku(ctx, req.(*RemoveSkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrolleyBusinessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trolley_business.TrolleyBusinessService",
	HandlerType: (*TrolleyBusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinSku",
			Handler:    _TrolleyBusinessService_JoinSku_Handler,
		},
		{
			MethodName: "RemoveSku",
			Handler:    _TrolleyBusinessService_RemoveSku_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/micro_mall_trolley_proto/trolley_business/trolley_business.proto",
}
